[build]
# Target musl-libc by default when running Cargo.
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "cargo-g++"
